language: ruby
rvm:
- 1.9.3
cache:
- bundler
script: bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: AOXu978ztYryCTQz8YqAPxMlLmjdotbDRUJYu/NsrGVLhNyOCh+JX5rUt9tUKNAMhqKMPwvbHLpdPFleQvIVn1BW2gPmEf+LNpheZ13vFrTHxx4m1OkemBi+r9BdD9kDEbtYLoGPJdLPFz4uHq86PqI2D69wdDYHCDiKIQ5reCc=
